### ISSUE TITLE
Show license information for models

### ISSUE THREAD

**Issue by botollama** [Jeffser/Alpaca#130]
having license will also help us

**Comment by Jeffser** [comment]
Hi, in the pull menu there's a button to visit the Ollama website for the model, I will also add a button to show the license directly

**Comment by botollama** [comment]
but having the info in the app easy good

**Comment by Jeffser** [comment]
I added a small disclaimer when downloading models, there's a button to check the Ollama website for each model, the license is clearly stated there, I don't want to add each license manually because they might change and that would cause problems

![image](https://github.com/Jeffser/Alpaca/assets/69224322/e303d024-eda1-4176-91bf-c6fab63f6a57)

**Comment by botollama** [comment]
By downloading this model you are accepting the licence terms of the model.
But i still think having a license written somewhere makes it a nice touch like.
Apache2 unlicensed or gpl2 or MIT and so on.
