### ISSUE TITLE
enter doesn't close renaming pop-up

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#212]
**Describe the bug**
When renaming a chat and when I press enter, the chat is renamed but the pop-up doesn't close

**Expected behavior**
pop-up close, bc when you click on cancel, I't doesn't cancel anything lol

**Screenshots**
[Capture vidéo du 2024-08-10 16-45-38.webm](https://github.com/user-attachments/assets/10e0d9db-9d22-4ac3-8818-71a1228f5d02)

**Additional context**
no

**Comment by Jeffser** [comment]
Hi I added default buttons to every dialog, they should be pressed when the user presses enter, now this doesn't work whilst the user is focusing a textbox so that's not ideal, afaik there's no way to directly close the dialog, so this is the best I can do rn

https://github.com/Jeffser/Alpaca/commit/ffe382aee270319b93cf8d83c7873e5e119971ab
