### ISSUE TITLE
being able to zoom in, zoom out

### ISSUE THREAD

**Issue by Hyphaed** [Jeffser/Alpaca#225]
add an option for being able to zoom in. zoom out the alpaca interface text

**Comment by Jeffser** [comment]
Hi unfortunately I can't add this since Alpaca follows Gnome's Human Interface Guidelines, the font size is decided by the system / user and shouldn't be modified on an app by app basis

**Comment by jdamboeck** [comment]
> Hi unfortunately I can't add this since Alpaca follows Gnome's Human Interface Guidelines, the font size is decided by the system / user and shouldn't be modified on an app by app basis

Many apps that follow these guidelines have the ability to have widgets with variable font size. Mostly in document viewer and code editors and such. 
For me it breaks the usability with this application. Yes i can overblow every font in the system OR just up the font size in the viewing area. Maybe if the text in chat would follow the document text property instead of the interface one there would be a way to control them separately.

Also the line-height is not a comfortable one for text consumption.
