### ISSUE TITLE
search trough chat

### ISSUE THREAD

**Issue by Hyphaed** [Jeffser/Alpaca#252]
add an otpion to search trough chat

**Comment by Jeffser** [comment]
To be honest with you it is going to be really hard to implement but I'll try

**Comment by Jeffser** [comment]
Hi, I have an update on this.

I added the message search feature, it search though every message block (text, code, tables)

It hides every message that doesn't have the search term and highlights where the text was found, for now the highlight only works with text blocks, I will add the highlight on tables and code later, because of that I will let this issue open

https://github.com/Jeffser/Alpaca/commit/5150fd769aef10b9d28e951ad696f977f1fa39eb

**Comment by Jeffser** [comment]
![image](https://github.com/user-attachments/assets/ec62c29c-b58f-44b5-9936-733ee0a934d4)

**Comment by Jeffser** [comment]
I'm happy with how it works right now, I will close this
