### ISSUE TITLE
Window size not adapting to large text

### ISSUE THREAD

**Issue by Zaglim** [Jeffser/Alpaca#301]
**Describe the bug**
When GNOME's Large Text Accessibility option is enabled, the content of the 'Manage Models' window is larger than the window itself. Horizontal scrolling is required to view the content completely.

**Expected behavior**
The Manage Models window expands in width when there is space available. When there is not space available, the text wraps as necessary so the content is not wider than the window. This is the behaviour of the preferences window.

**Screenshots**
Without large text:
![Screenshot of Alpaca open to Manage Models, with Large Text disabled in the GNOME desktop environment](https://github.com/user-attachments/assets/33676bc2-8a9e-46d5-a3d6-992c702e0954)

With large text (undesirable behavior):
![Screenshot of Alpaca open to Manage Models, with Large Text enabled in the GNOME desktop environment](https://github.com/user-attachments/assets/b1524cff-a546-468c-9c8f-528cc42ea325)

Preferences without large text:
![Slim Preferences with Large Text disabled](https://github.com/user-attachments/assets/7abfb2fb-4a29-41c1-9527-24cf70f029cb)

Preferences with large text (demonstrating expected behaviour):
![Slim Preferences with Large Text enabled](https://github.com/user-attachments/assets/9e1e53ab-956d-4d68-a716-7a9ca64a88ae)

**Debugging information**
n/a - I don't think this is applicable for this bug report. Please let me know if it is, or if this issue is better as a feature request.

**Comment by Jeffser** [comment]
Hi, I have an update on this. I made the dialog resizeable so it looks good now

![image](https://github.com/user-attachments/assets/b6aa7512-dc85-49df-8c5f-58dd5d6661d4)

Problem is, now that it doesn't have a size limit this happens when the window is really small, this will gravely affect phones

![image](https://github.com/user-attachments/assets/cd78ecf2-dad6-4b30-9f9e-4a61d17eaff5)

https://github.com/Jeffser/Alpaca/commit/3653af7b81909b806c5d9217b1a7b1bd8e761c60

**Comment by Jeffser** [comment]
Hi, I found out what was the issue, the titles didn't have wrap enabled and there's a model with a really big name, that's why the dialog wasn't resizing correctly.

It adapts perfectly fine now, thanks for the report

https://github.com/Jeffser/Alpaca/commit/70e4d8f407cfba0fc80fcbf1cd0d077ca06c00f8
