### ISSUE TITLE
export chat to md

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#354]
add a button in the submenu

**Comment by Jeffser** [comment]
sounds interesting, I'll look into it, thanks!

**Comment by Jeffser** [comment]
Hi, I finished implementing this, now when you export the chat as a tar file it will have a markdown file inside of it, I can't export just the markdown file because it might also include documents and images which will be included inside the tar, it also simplifies the implementation honestly

[Screencast From 2024-12-15 15-36-31.webm](https://github.com/user-attachments/assets/9e303609-c5b0-4990-b3fa-ab40876506db)
