### ISSUE TITLE
Allow editing of model's messages

### ISSUE THREAD

**Issue by Axenide** [Jeffser/Alpaca#373]
**Is your feature request related to a problem? Please describe.**
I think allowing the user to edit the model's messages would be a great adition. Open WebUI has this feature and it helps getting the results the user wants.

**Describe the solution you'd like**
Allowing the user to edit the model's messages.

**Describe alternatives you've considered**
None

**Additional context**
This allows more control over the model's text generation.

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion, I didn't do this previously because of all the space the buttons took in every message but I just redesign the message widget so now I can add the edit button!

![image](https://github.com/user-attachments/assets/ed2b1b8d-7dc4-448b-a622-b4b449d0524b)

https://github.com/Jeffser/Alpaca/commit/d4f931e3d7adb51dd63cb05ec3ab80540b3d92c3

**Comment by Axenide** [comment]
Amazing, thanks!
