### ISSUE TITLE
Name Change Suggestions

### ISSUE THREAD

**Issue by Jeffser** [Jeffser/Alpaca#93]
Hi, it has come to my attention that there are some people who really don't like the name Alpaca because it's too generic and there are some unrelated tools already called Alpaca, so I'm open to change the name.

I need to keep the Llama / Alpaca theme because there are people working on a new icon and I don't want to discard their great work
https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/55

I also want to point to [this](https://github.com/Jeffser/Alpaca/issues/4) early issue, someone asked me to change the name because of [Alpaka](https://invent.kde.org/utilities/alpaka)

I need the name to be something [Gnome'ish](https://circle.gnome.org/) so, something clear that doesn't use any technicalities, so I don't want stuff like "AIpaca" 

I want to make the new name official for the 1.0.0 version, thanks

**Comment by BadKiko** [comment]
I think we need to ask the ai for options 😁

**Comment by BadKiko** [comment]
I actually like the name "Alpaca", it's minimalist in the GNOME style and basically describes the essence of the application so I don't know if this change is necessary

**Comment by loulou64490** [comment]
Or change it to Alpaga, the french version 🥖🥖🥖🥖🥖 (because it's will be pronounced differently from Alpaka)

**Comment by not-a-dev-stein** [comment]
+1 for keeping the current name, I think it fits pretty well in the GNOME environment, also Alpaka exists but hasn't been widespread released yet, so I don't think there's a problem in going first 😅 

Alpaga is a nice alternative that would also fit the idea in the old folks minds that "apps with K are for KDE and apps with G are for GNOME"

**Comment by loulou64490** [comment]
Yes, k for kde and g for gnome !!!

**Comment by TylerLaBree** [comment]
Here are the [gnome app naming guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html).

I feel that Alpaca and Alpaga likely fit these criteria, with the possible exception of "Be easy to pronounce". I feel like that one is subjective, and largely depends on the language(s) one learned first. I don't know how exactly to pronounce Alpaga, but someone who doesn't speak English as a first language might not know how to pronounce Alpaca.

Also, regarding the name being too generic, I disagree. "Alpaca" doesn't exactly describe what the app does, but that's typical of a gnome style app name, and if we wanted to describe (or hint at) the app's function, we'd likely need to drop the animal theme. The ideas I have for that are Assistant, Sidekick, or Echo.

There's another rule that might give us trouble, "avoid puns and inside jokes". Alpaca isn't really a pun, but it's a reference to Ollama (which the user might not know), and Ollama comes from LLaMA, which is a pun on LLM. I think we're probably fine here, but it might be useful to check.

Finally, if we want to avoid Alpaca because of Alpaka (which the guidelines sort of encourages), we could go for another camelid, the category that contains alpacas and llamas. Naming the app **Camel** would solve this, and maybe some of the work done by icon designers could remain. I'm actually really starting to like this one.

I still think Alpaca is a great name.

**Comment by Jeffser** [comment]
well thanks for the suggestions, but it appears like you guys don't want to change the name, I also don't want to change it, yesterday I found a forum talking about how they hate "developers using generic and already used names" whilst referring specifically to Alpaca, I can't seem to find that forum now, so I guess it really doesn't matter.

So I will keep the name for now, thanks
